spring.application.name=myapp
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Myapp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configurations (optional but commonly used)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=doilduizg
cloudinary.api-key=962162384327677
cloudinary.api-secret=puyolFGnrI2mX2L5FwbLlrVlOJ0

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB