spring.application.name=myapp

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Myapp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configurations (optional but commonly used)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Open-in-view x?b?rdarl???n? söndürm?k üçün ?lav? edirik:
spring.jpa.open-in-view=false

# Tomcat Session ID yaratma gecikm?sini aradan qald?ran optimizasiya
# Bu, "SecureRandom" x?b?rdarl???n? h?ll edir.
java.security.egd=file:/dev/./urandom

cloudinary.cloud-name=doilduizg
cloudinary.api-key=962162384327677
cloudinary.api-secret=puyolFGnrI2mX2L5FwbLlrVlOJ0

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# E-Mail Konfiqurasiyas?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ismayanar27@gmail.com
spring.mail.password=hsjpibcykxjxuzol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# ?laq? Mesajlar? üçün Admin Mail Ünvan? (ContactServiceImpl t?r?find?n oxunur)
admin.email.recipient=ismayanar27@gmail.com

# T?hlük?sizlik Konfiqurasiyas? Düz?li?i
spring.security.user.name=admin
spring.security.user.password={noop}12345
spring.security.user.roles=ADMIN
